# Generated by Django 3.1.7 on 2021-02-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0002_auto_20210222_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artista.artista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='data_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='obesrvacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
