# Generated by Django 3.1.7 on 2021-02-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0003_auto_20210222_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='artista',
        ),
    ]
