# Generated by Django 3.1.7 on 2021-02-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_remove_musica_artista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='musica',
            options={'verbose_name_plural': 'Musicas'},
        ),
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artista.artista'),
        ),
    ]
