# Generated by Django 3.1.7 on 2021-02-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0005_auto_20210222_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='musica',
            name='data_Post_Musc',
            field=models.DateTimeField(),
        ),
    ]
