# Generated by Django 3.1.7 on 2021-02-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0007_auto_20210222_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
