# Generated by Django 3.1.7 on 2021-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0012_auto_20210222_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='data_Post_Musc',
            field=models.DateField(verbose_name=True),
        ),
    ]
