# Generated by Django 3.1.7 on 2021-02-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0014_auto_20210222_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
    ]
