# Generated by Django 3.1.7 on 2021-02-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0016_auto_20210222_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='spotufy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musica',
            name='youtube',
            field=models.BooleanField(default=True),
        ),
    ]
