# Generated by Django 3.1.7 on 2021-02-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0017_auto_20210222_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='spotufy',
            new_name='spotify',
        ),
        migrations.AlterField(
            model_name='musica',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
    ]
