# Generated by Django 3.1.7 on 2021-02-24 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0019_auto_20210224_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='artista.artista'),
        ),
    ]
